---
- name: Install Apache2 and PHP Packages on Ubuntu
  hosts: your_target_host  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Update repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP packages
      apt:
        name:
          - php-mbstring
          - php-zip
          - php-gd
          - php-json
          - php-curl
          - libapache2-mod-php8.1
        state: present
