---
- name: Check Updates and Install Bind9
  hosts: all
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Update repository cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Update repository cache (CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install Bind9 (Ubuntu/Debian)
      apt:
        name: bind9
        state: latest
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Bind9 (CentOS)
      yum:
        name: bind
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
