---
- name: Install PHP and Modules on Ubuntu
  hosts: your_target_host  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Install PHP and modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-mbstring
          - php-zip
          - php-gd
          - php-json
          - php-curl
        state: present
