---
- name: Host VM
  hosts: all
  become: yes 

  tasks:
    - name: Update repository cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Update repository cache (CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install the latest PHP version (Ubuntu/Debian)
      apt:
        name: php
        state: latest
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install the latest PHP version (CentOS)
      yum:
        name: php
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
