---
- name: Install Apache2 and phpMyAdmin
  hosts: all  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Update repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install phpMyAdmin dependencies
      apt:
        name:
          - php-mbstring
          - php-zip
          - php-gd
          - php-json
          - php-curl
          - libapache2-mod-php8.1
        state: present

    - name: Install phpMyAdmin
      apt:
        name: phpmyadmin
        state: present

    - name: Enable mbstring module
      command: phpenmod mbstring
