---
- name: Install Portainer via Docker
  hosts: all  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Install Docker (Ubuntu/Debian)
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Docker (CentOS)
      yum:
        name: docker
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Portainer Docker image
      command: docker pull portainer/portainer-ce
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ("docker" in ansible_facts.packages)

    - name: Create Portainer Container
      command: docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer-ce
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ("docker" in ansible_facts.packages)
