---
- name: Install Portainer Latest via Docker
  hosts: all  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Install Docker (Ubuntu/Debian)
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Docker (CentOS)
      yum:
        name: docker
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Portainer Docker image
      community.general.docker_image:
        name: portainer/portainer-ce:latest
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ("docker" in ansible_facts.packages)

    - name: Create Portainer Container
      community.general.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ("docker" in ansible_facts.packages)
