---
- name: Update, Install qemu-agent, Start and Enable Services, Reboot, Wait, and Check Uptime
  hosts: all # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Update repository cache on Debian
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - name: Update repository cache on CentOS
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install qemu-guest-agent on Debian
      apt:
        name: qemu-guest-agent
        state: present
      when: ansible_distribution == 'Debian'

    - name: Install qemu-guest-agent on CentOS
      yum:
        name: qemu-guest-agent
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Start qemu-guest-agent service on Debian
      service:
        name: qemu-guest-agent
        state: started
      when: ansible_distribution == 'Debian'

    - name: Start qemu-guest-agent service on CentOS
      service:
        name: qemu-ga
        state: started
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Reboot the machine
      command: reboot
      async: 0
      poll: 0
      when: ansible_distribution == 'Debian' or ansible_distribution == 'CentOS'

    - name: Wait for 300 seconds
      pause:
        seconds: 300
      when: ansible_distribution == 'Debian' or ansible_distribution == 'CentOS'

    - name: Check Uptime
      command: uptime
      register: uptime_output
      when: ansible_distribution == 'Debian' or ansible_distribution == 'CentOS'

    - name: Display Uptime
      debug:
        var: uptime_output.stdout_lines
      when: ansible_distribution == 'Debian' or ansible_distribution == 'CentOS'
