---
- name: Reboot VM
  hosts: all
  become: yes # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Reboot the VM
      reboot:
        reboot_timeout: 300
        test_command: uptime