---
- name: Update and Upgrade Ubuntu
  hosts: all  # Ganti dengan nama atau grup host target Anda
  become: yes  # Untuk mendapatkan akses superuser (biasanya root)

  tasks:
    - name: Update repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
